replicaCount: 2

image:
  repository: bpsnifer/lesson-5-hw-users

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths: 
        - /otusapp($|/)(.*)

service:
  type: NodePort
  port: "8080"

postgresql:
  enabled: true
  postgresqlUsername: user
  postgresqlPassword: p@55w0rd
  postgresqlDatabase: lesson5
  service:
    port: "5432"