apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app.kubernetes.io/name: users
    app.kubernetes.io/version: "v1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: users
  template:
    metadata:
      labels:
        app.kubernetes.io/name: users
      annotations:
        checksum/config: f936ff1b07449954bf047120beeea18df8be64378094a628043a44857961221d
    spec:
      containers:
        - name: users
          image: "bpsnifer/lesson-5-hw-users:v1"
          ports:
            - name: srvport
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /health
              port: srvport
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /health
              port: srvport
          envFrom:
          - configMapRef:
              name: users-config
          - secretRef:
              name: users-secret
