apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    app: postgresql
    chart: postgresql-8.9.1
    heritage: "Helm"
type: Opaque
data:
  postgresql-password: "cEA1NXcwcmQ="
---
apiVersion: v1
kind: Secret
metadata:
  name: users-secret
type: Opaque
data:
  DB_HOST: "cG9zdGdyZXNxbDo1NDMy"
  DB_USER: "dXNlcg=="
  DB_PASSWORD: "cEA1NXcwcmQ="
  DB_BASE: "bGVzc29uNQ=="
